
[[constraint]]
  name = "github.com/docker/distribution"
  branch = "master"

[[constraint]]
  name = "github.com/docker/go-connections"
  version = "0.3.0"

[[constraint]]
  name = "github.com/docker/go-units"
  version = "0.3.2"

[[constraint]]
  name = "github.com/docker/notary"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "0.4.0"

[[constraint]]
  name = "github.com/opencontainers/go-digest"
  branch = "master"

[[constraint]]
  name = "github.com/opencontainers/image-spec"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"
