[[constraint]]
  branch = "v0.4.5"
  name = "github.com/Microsoft/go-winio"
[[constraint]]
  branch = "v1.0.3"
  name = "github.com/sirupsen/logrus"
[[constraint]]
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"
  name = "github.com/docker/distribution"
[[constraint]]
  revision = "d7b4c7e0eac223eda54940adbb4c44bf71ec039c"
  name = "github.com/docker/docker"
[[constraint]]
  revision = "3ede32e2033de7505e6500d6c868c2b9ed9f169d"
  name = "github.com/docker/go-connections"
[[constraint]]
  revision = "9e638d38cf6977a37a8ea0078f3ee75a7cdb2dd1"
  name = "github.com/docker/go-units"
[[constraint]]
  revision = "9cbd2a1374f46905c68a4eb3694a130610adc62a"
  name = "github.com/docker/libtrust"
[[constraint]]
  revision = "a6d0ee40d4207ea02364bd3b9e8e77b9159ba1eb"
  name = "github.com/opencontainers/go-digest"
[[constraint]]
  revision = "372ad780f63454fbbbbcc7cf80e5b90245c13e13"
  name = "github.com/opencontainers/image-spec"
[[constraint]]
  revision = "3f2f8b84a77f73d38244dd690525642a72156c64"
  name = "github.com/opencontainers/runc"
[[constraint]]
  revision = "839d9e913e063e28dfd0e6c7b7512793e0a48be9"
  name = "github.com/pkg/errors"
[[constraint]]
  revision = "3fbbcd23f1cb824e69491a5930cfeff09b12f4d2"
  name = "golang.org/x/crypto"
[[constraint]]
  revision = "7dcfb8076726a3fdd9353b6b8a1f1b6be6811bd6"
  name = "golang.org/x/net"
[[constraint]]
  revision = "07c182904dbd53199946ba614a412c61d3c548f5"
  name = "golang.org/x/sys"


# notary
[[constraint]]
  branch = "master"
  name = "github.com/docker/notary"
[[constraint]]
  revision = "d30aec9fd63c35133f8f79c3412ad91a3b08be06"
  name = "github.com/docker/go"
